import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Employee Management",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="flex items-start justify-between">
      <Sidebar />
      <main className="h-full w-full">
        <div className="border-b-2 p-4 ">
          <Header />
        </div>
        <div className="p-4">{children}</div>
      </main>
    </div>
  );
}
